#!/usr/bin/env bash
set -e

cd /home/build

echo "Building executable..."
stack build

mkdir -p out
echo "Copying executables..."
cp "$(stack path --local-install-root)"/bin/* out/

echo "Build finished! Executables available in \"out/\""
